### PR TITLE
adora84

### PR DESCRIPTION
**Pull request by adora84**

### CODE REVIEW

**Comment by yvan-sraka** [comment]
**CONGRATULATIONS :cake: !**

**Comment by yvan-sraka** [comment]
Maybe you have to check the **TraviS CI** logs: https://travis-ci.org/simplonco/fizzbuzz/builds/124755523

```
$ jasmine-node *.spec.js --verbose
buzz
Exception loading: /home/travis/build/simplonco/fizzbuzz/fizzbuzz.spec.js
[TypeError: require(...) is not a function]
```

**Comment by adora84** [comment]
can you check it out

**Comment by yvan-sraka** [comment]
On GitHub there is never any reason to remove a repository :disappointed: ..

**Pull request closed without merging**
